### PR TITLE
Add LC-MS preprocessing with xcms tutorial

### PR DESCRIPTION
**Pull request by jorainer**

### CODE REVIEW

**Comment by lgatto** [comment]
OK to link to the rendered vignette rather than the Github repo? 

I would also suggest that, as far as possible, we try to stick to RforMS packages.

**Comment by jorainer** [comment]
Sure - fine for me. Are you adding that or should I?

**Comment by lgatto** [comment]
I've done it already - just wanted to make sure you were OK with it.

**Comment by jorainer** [comment]
Thanks!

**Pull request merged**
